name: first workflow
on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
      - name: welcome message
        run: echo "Welcome to the first workflow on push event!"

      - name: install cowsay
        run: sudo apt-get install -y cowsay

      - name: display message with cowsay
        run: |
          echo "Welcome to the first workflow on push event!" | cowsay > shady.txt

      - name: artifact upload
        uses: actions/upload-artifact@v4.6.2
        with:
          name: shady-artifact
          path: shady.txt

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2

      - name: download artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: shady-artifact
          path: .

      - name: test file shady.txt
        run: grep -i "welcome" shady.txt || echo "No welcome message found in shady.txt"
